name: route
description: Wrapper for go_router.
version: 1.0.0
homepage: https://github.com/flutter-packagist/route

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^12.0.1
  log_wrapper:
    version: 1.0.0
    hosted:
      name: log_wrapper
      url: http://192.168.8.75:4000/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
